# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cb971e705b3a1e07e330d50f4889c317cb6771dcb48882e0c519aedfbc0e01af856a89dce19eed846806e6097e888ddf166945dab18586140a784b156a5505f

test:
  secret_key_base: b3b26d3d389b7e8f8a39fe04131443bd8f6632798880a30ba5222218691c6350b8fc2ace25d14a9fea5da0e817ff4bc9018a7022a894e8d4150fc651d8cf2aec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
